name: Deploy to Breadberry Pi

on:
    push:
        branches:
            - main
    # You can deploy on any branch if needed in the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - name: Build client & server
              run: | # CI=false to ignore warnings and not fail the build
                  export CI=false 
                  cd client && npm install && npm run build
                  cd ..
                  cd server && npm install
                  cd ..

    deploy:
        runs-on: self-hosted
        needs: build
        steps:
            - name: Start client & server
              run: |
                  export HAI405I_HOST=http://bottle.laboulangerie.net:4242
                  export HAI405I_PORT=4242
                  pm2 start HAI405I-BACK
                  cd client && RUNNER_TRACKING_ID="" && npm run serve &
