name: Deploy to Breadberry Pi

on:
    push:
        branches:
            - main
    # You can deploy on any branch if needed in the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3

    deploy:
        runs-on: self-hosted
        needs: build

        steps:
            - name: Stop client & server
              run: |
                  cd client && pnpm install && pnpm run build
                  cd ..
                  cd server && pnpm install
                  cd ..

            - name: Start client & server
              run: |
                  cd client && serve -s build -l 4000
                  pm2 start HAI405I-BACK
