name: Deploy to Breadberry Pi

on:
    push:
        branches:
            - using-docker
            - main
    # You can deploy on any branch if needed in the Actions tab
    workflow_dispatch:

jobs:
    deploy-docker:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - name: Build docker compose
              run: docker compose up --force-recreate --build -d
            - name: clear old docker images
              run: docker image prune -f
